name: Merge
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker run -v $(pwd):/work --workdir /work -ti centos:centos8 /bin/bash -c 'yum install -y rpm-build $(cat automation/build-artifacts.packages) && ./automation/build-artifacts-manual.sh'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: exported-artifacts/
