name: build
on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
          - name: centos-stream-10
            shortcut: cs10
            container-name: el10stream
    name: ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    steps:
      - name: Checkout
        uses: ovirt/checkout-action@main
      - name: Make distclean
        run: make distclean
      - name: Make dist
        run: make dist
      - name: Make srpm
        run: make srpm
      - name: Make RPM
        run: make rpm
      - name: Collect artifacts
        run: |
          mkdir -p exported-artifacts
          find tmp.repos -iname \*rpm -exec mv "{}" exported-artifacts/ \;
      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts
